# Generated by Django 5.2.4 on 2026-08-03 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judging', '0003_rename_evaluation_status'),
        ('rubrics', '0003_rubric_is_active_rubric_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='llama3, mistral, qwen…', max_length=100)),
                ('model_version', models.CharField(blank=True, max_length=60)),
                ('prompt_version', models.CharField(blank=True, help_text='Track prompt-engineering iterations', max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('raw_output', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_runs', to='judging.evaluation')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_runs_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AICriterionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('evidence', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_results', to='rubrics.rubriccriterion')),
                ('ai_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ai_engine.aievaluationrun')),
            ],
            options={
                'ordering': ['criterion__display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='aievaluationrun',
            index=models.Index(fields=['status'], name='ix_ai_run_status'),
        ),
        migrations.AddConstraint(
            model_name='aicriterionresult',
            constraint=models.UniqueConstraint(fields=('ai_run', 'criterion'), name='unique_ai_result_per_criterion'),
        ),
    ]
