# Generated by Django 5.2.4 on 2026-07-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('judge_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('comments', models.TextField(blank=True)),
                ('reasoning', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['criterion__display_order'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_status', models.CharField(choices=[('pending', 'Pending'), ('ai_complete', 'AI Complete'), ('judge_reviewing', 'Judge Reviewing'), ('approved', 'Approved'), ('published', 'Published')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
