# Generated by Django 5.2.15 on 2026-09-21 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0004_appeal_scoreoverride_evaluation_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='grounds',
            field=models.CharField(choices=[('rubric_misapplied', 'The rubric was not applied as published'), ('wrong_document', 'The wrong version or document was scored'), ('penalty_misapplied', 'A penalty was applied in error'), ('arithmetic', 'Scores were totalled incorrectly'), ('conflict', 'The judge had an undeclared conflict of interest'), ('process', 'Another departure from the published process')], default='process', max_length=30),
        ),
        migrations.AddField(
            model_name='appeal',
            name='second_judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals_reviewing', to=settings.AUTH_USER_MODEL),
        ),
    ]
