# Generated by Django 5.2.4 on 2026-08-12 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_v1_schema_alignment'),
        ('competitions', '0003_remap_status_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='cell_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='enterprise',
            field=models.CharField(blank=True, choices=[('a', 'Enterprise A — Financial'), ('b', 'Enterprise B — Healthcare')], max_length=1),
        ),
        migrations.AddField(
            model_name='team',
            name='responsibility',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='track',
            field=models.CharField(blank=True, choices=[('cloud', 'Cloud'), ('application', 'Application'), ('ai', 'AI')], help_text='Cloud, Application or AI specialisation.', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('cell_id', ''), _negated=True), fields=('competition', 'cell_id'), name='unique_cell_per_competition'),
        ),
    ]
