# Generated by Django 5.2.4 on 2026-09-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_team_cell_id_team_enterprise_team_responsibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
