# Generated by Django 5.2.15 on 2026-09-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_team_rejection_reason'),
        ('accounts', '0007_track_and_join_requests'),
    ]

    operations = [
    ]
