# Generated by Django 5.2.15 on 2026-09-21 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20260920_2228'),
        ('competitions', '0009_remove_applicationbrief_unique_brief_per_competition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_cell_per_competition',
        ),
        migrations.AddField(
            model_name='team',
            name='application_brief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='competitions.applicationbrief'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_identifier',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_security_specialist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='enterprise',
            field=models.CharField(blank=True, choices=[('a', 'ENTA — JengaBank A'), ('b', 'ENTB — JengaBank B')], max_length=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='track',
            field=models.CharField(blank=True, choices=[('application', 'Application'), ('ai', 'AI')], help_text='Application or AI specialisation.', max_length=15),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('captain', 'Captain'), ('member', 'Member'), ('reserve', 'Reserve')], default='member', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('cell_id', ''), _negated=True), fields=('competition', 'enterprise', 'cell_id'), name='unique_cell_per_enterprise'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('team_identifier', ''), _negated=True), fields=('team_identifier',), name='unique_team_identifier'),
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.team'),
        ),
        migrations.DeleteModel(
            name='TeamJoinRequest',
        ),
        migrations.AddConstraint(
            model_name='teaminvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('team', 'email'), name='one_pending_invitation_per_email_per_team'),
        ),
    ]
