# Generated by Django 5.2.4 on 2026-08-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_v1_schema_alignment'),
        ('competitions', '0002_competition_created_by_competition_updated_at_and_more'),
        ('submissions', '0002_seed_submission_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionfile',
            name='checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='submissionfile',
            name='file_size',
            field=models.BigIntegerField(default=0, help_text='Size in bytes'),
        ),
        migrations.AddField(
            model_name='submissionfile',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='ix_submission_status'),
        ),
    ]
