# Generated by Django 5.2.4 on 2026-08-04 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submissionfile_checksum_submissionfile_file_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped (unsupported format)')], default='pending', max_length=20)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('content', models.JSONField(blank=True, null=True)),
                ('text', models.TextField(blank=True)),
                ('parser_version', models.CharField(blank=True, max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('submission_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed', to='submissions.submissionfile')),
            ],
            options={
                'ordering': ['-parsed_at'],
                'indexes': [models.Index(fields=['status'], name='ix_parsed_status')],
            },
        ),
    ]
