# Generated by Django 5.2.4 on 2026-08-16 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_competition_phase_applicationbrief'),
        ('submissions', '0005_seed_supporting_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='application_brief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='competitions.applicationbrief'),
        ),
        migrations.AddField(
            model_name='submission',
            name='selection_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('shortlisted', 'Shortlisted'), ('selected', 'Selected to Build'), ('rejected', 'Not Selected')], default='pending', help_text='Proposal outcome; scoring itself lives in the evaluation.', max_length=15),
        ),
    ]
