# Generated by Django 5.2.4 on 2026-08-18 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_submission_application_brief_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='late_by',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='marking_excluded',
            field=models.BooleanField(default=False, help_text='Judges have declined to mark this submission.'),
        ),
        migrations.AddField(
            model_name='submission',
            name='marking_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('index', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='submissions/figures/%Y/%m/')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('image_format', models.CharField(blank=True, max_length=10)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('caption', models.CharField(blank=True, help_text='Nearest heading or preceding line.', max_length=300)),
                ('parsed_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='submissions.parseddocument')),
            ],
            options={
                'ordering': ['page', 'index'],
                'constraints': [models.UniqueConstraint(fields=('parsed_document', 'page', 'index'), name='unique_figure_position')],
            },
        ),
    ]
