# Generated by Django 5.2.15 on 2026-09-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_submission_is_late_submission_late_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='selection_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('shortlisted', 'Shortlisted'), ('selected', 'Selected to Build'), ('reserve', 'Reserve'), ('rejected', 'Not Selected')], default='pending', help_text='Proposal outcome; scoring itself lives in the evaluation.', max_length=15),
        ),
    ]
