# Generated by Django 5.2.15 on 2026-09-21 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_three_proposal_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('breach', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('percent_strict', models.PositiveSmallIntegerField(default=0)),
                ('percent_standard', models.PositiveSmallIntegerField(default=0)),
                ('percent_relaxed', models.PositiveSmallIntegerField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='late_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='late_accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_submissions_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='late_accepted_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='submission',
            name='late_evidence_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='late_upload_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('returned_incomplete', 'Returned incomplete'), ('under_review', 'Under Review'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ProposalCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ok', 'Complete'), ('incomplete', 'Front matter missing'), ('not_checked', 'Not checked')], default='not_checked', max_length=15)),
                ('front_matter', models.JSONField(blank=True, default=list)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('body_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('submission_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structure_check', to='submissions.submissionfile')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveSmallIntegerField()),
                ('note', models.CharField(blank=True, max_length=300)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('breach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='submissions.penaltyschedule')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='submissions.submission')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
