# Generated by Django 5.2.4 on 2026-08-03 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0004_appeal_scoreoverride_evaluation_updated_at_and_more'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_generated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('team_feedback', 'Team Feedback'), ('judge_report', 'Judge Report'), ('competition_summary', 'Competition Summary'), ('analytics', 'Analytics')], default='team_feedback', max_length=30),
        ),
        migrations.AlterField(
            model_name='report',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='judging.evaluation'),
        ),
    ]
