# Generated by Django 5.2.4 on 2026-08-18 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('submission', 'Submission'), ('competition', 'Competition'), ('judging', 'Judging'), ('admin', 'Administration')], max_length=20)),
                ('action', models.CharField(choices=[('login_success', 'Signed in'), ('login_failed', 'Failed sign-in'), ('logout', 'Signed out'), ('role_changed', 'Role changed'), ('file_uploaded', 'Document uploaded'), ('submission_submitted', 'Submission finalised'), ('file_downloaded', 'Document downloaded'), ('proposal_selection', 'Proposal outcome set'), ('marking_changed', 'Marking eligibility changed'), ('competition_created', 'Competition created'), ('competition_updated', 'Competition updated'), ('lifecycle_changed', 'Lifecycle changed'), ('score_overridden', 'Score overridden')], max_length=40)),
                ('target_type', models.CharField(blank=True, max_length=60)),
                ('target_id', models.CharField(blank=True, max_length=40)),
                ('target_label', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='ix_audit_created'), models.Index(fields=['action'], name='ix_audit_action'), models.Index(fields=['category'], name='ix_audit_category'), models.Index(fields=['actor'], name='ix_audit_actor')],
            },
        ),
    ]
