# Generated by Django 5.2.4 on 2026-07-13 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('submissions', '0002_seed_submission_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='competitions.competition')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubrics_created', to=settings.AUTH_USER_MODEL)),
                ('submission_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubrics', to='submissions.submissiontype')),
            ],
            options={
                'ordering': ['competition', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maximum_score', models.PositiveIntegerField(default=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='rubrics.rubric')),
            ],
            options={
                'verbose_name_plural': 'rubric criteria',
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('rubric', 'criterion'), name='unique_criterion_per_rubric')],
            },
        ),
    ]
