# Generated by Django 5.2.4 on 2026-08-03 17:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0002_rename_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rubric',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rubriccriterion',
            name='criterion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rubriccriterion',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='rubriccriterion',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.UniqueConstraint(fields=('rubric', 'display_order'), name='unique_order_per_rubric'),
        ),
    ]
