# Generated by Django 5.2.4 on 2026-07-13 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('theme', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('registration', 'Registration Open'), ('active', 'Active'), ('judging', 'Judging'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='competitions.competition')),
            ],
            options={
                'verbose_name_plural': 'competition categories',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('competition', 'name'), name='unique_category_per_competition')],
            },
        ),
        migrations.CreateModel(
            name='CompetitionPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='competitions.competition')),
            ],
            options={
                'ordering': ['order', 'start_date'],
                'constraints': [models.UniqueConstraint(fields=('competition', 'name'), name='unique_phase_per_competition')],
            },
        ),
    ]
