# Generated by Django 5.2.4 on 2026-08-12 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_team_cell_id_team_enterprise_team_responsibility_and_more'),
        ('competitions', '0003_remap_status_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. APP-01', max_length=20, unique=True)),
                ('track', models.CharField(choices=[('cloud', 'Cloud'), ('application', 'Application'), ('ai', 'AI')], max_length=15)),
                ('name', models.CharField(max_length=200)),
                ('objective', models.TextField()),
                ('expected_evidence', models.TextField(blank=True)),
                ('success_condition', models.TextField()),
                ('red_points', models.IntegerField(default=0)),
                ('blue_points', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['track', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. APP-07', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('objective', models.TextField(blank=True)),
                ('max_points', models.PositiveIntegerField(default=100)),
                ('success_conditions', models.JSONField(blank=True, default=list, help_text='List of condition strings.')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='accounts.team')),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('team', 'code'), name='unique_objective_per_team')],
            },
        ),
        migrations.CreateModel(
            name='TargetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(blank=True, help_text='In-scope endpoint or address.', max_length=255)),
                ('access_notes', models.TextField(blank=True, help_text='VPN profile, credentials, caveats.')),
                ('is_active', models.BooleanField(default=False, help_text='Engagement window open.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_assignments', to='competitions.competition')),
                ('red_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_assignments', to='accounts.team')),
                ('target_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacker_assignments', to='accounts.team')),
            ],
            options={
                'ordering': ['red_team', 'target_team'],
                'constraints': [models.UniqueConstraint(fields=('red_team', 'target_team'), name='unique_target_assignment')],
            },
        ),
    ]
