# Generated by Django 5.2.4 on 2026-08-16 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_seed_attack_scenarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='phase',
            field=models.CharField(choices=[('registration', 'Registration'), ('build', 'Build'), ('live', 'Live Competition'), ('judging', 'Judging')], default='registration', help_text='Drives which dashboard teams land on.', max_length=20),
        ),
        migrations.CreateModel(
            name='ApplicationBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. APP-A1', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('enterprise', models.CharField(blank=True, choices=[('a', 'Enterprise A — Financial'), ('b', 'Enterprise B — Healthcare')], max_length=1)),
                ('track', models.CharField(choices=[('cloud', 'Cloud'), ('application', 'Application'), ('ai', 'AI')], default='application', max_length=15)),
                ('summary', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True, help_text='One requirement per line.')),
                ('proposal_cap', models.PositiveIntegerField(default=20, help_text='Maximum proposals accepted for this application.')),
                ('is_open', models.BooleanField(default=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_briefs', to='competitions.competition')),
            ],
            options={
                'ordering': ['enterprise', 'code'],
                'constraints': [models.UniqueConstraint(fields=('competition', 'code'), name='unique_brief_per_competition')],
            },
        ),
    ]
