# Generated by Django 5.2.4 on 2026-08-18 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_competition_phase_applicationbrief'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissions_open', models.BooleanField(default=True, help_text='Teams may upload documents.')),
                ('judging_open', models.BooleanField(default=False, help_text='Judges may score submissions.')),
                ('results_published', models.BooleanField(default=False, help_text='Teams can see final scores and feedback.')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('build_deadline', models.DateTimeField(blank=True, null=True)),
                ('submission_deadline', models.DateTimeField(blank=True, null=True)),
                ('max_proposals_per_team', models.PositiveIntegerField(default=1)),
                ('default_proposal_cap', models.PositiveIntegerField(default=20, help_text='Applied to new application briefs.')),
                ('appeal_window_days', models.PositiveIntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings_row', to='competitions.competition')),
            ],
            options={
                'verbose_name_plural': 'competition settings',
            },
        ),
    ]
