# Generated by Django 5.2.4 on 2026-09-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_competitionsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsettings',
            name='member_grace_days',
            field=models.PositiveIntegerField(default=7, help_text='Days a team has to replace a departed member before its registration is reviewed again.'),
        ),
    ]
