# Generated by Django 5.2.15 on 2026-09-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_competitionsettings_member_grace_days'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applicationbrief',
            name='unique_brief_per_competition',
        ),
        migrations.AddField(
            model_name='applicationbrief',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationbrief',
            name='red_exposure',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicationbrief',
            name='code',
            field=models.CharField(help_text='e.g. APP03', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicationbrief',
            name='enterprise',
            field=models.CharField(blank=True, choices=[('a', 'ENTA — JengaBank A'), ('b', 'ENTB — JengaBank B')], max_length=1),
        ),
        migrations.AlterField(
            model_name='applicationbrief',
            name='proposal_cap',
            field=models.PositiveIntegerField(default=10, help_text='Each published brief accepts up to ten proposals (Guide section 4).'),
        ),
        migrations.AlterField(
            model_name='applicationbrief',
            name='requirements',
            field=models.TextField(blank=True, help_text="'Security it must get right' -- one requirement per line."),
        ),
        migrations.AlterField(
            model_name='applicationbrief',
            name='track',
            field=models.CharField(choices=[('application', 'Application'), ('ai', 'AI')], default='application', max_length=15),
        ),
        migrations.AlterField(
            model_name='attackscenario',
            name='track',
            field=models.CharField(choices=[('application', 'Application'), ('ai', 'AI')], max_length=15),
        ),
        migrations.AddConstraint(
            model_name='applicationbrief',
            constraint=models.UniqueConstraint(fields=('competition', 'enterprise', 'code'), name='unique_brief_per_enterprise'),
        ),
    ]
