# Generated by Django 5.2.15 on 2026-09-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_retire_cloud_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsettings',
            name='enforcement_level',
            field=models.CharField(choices=[('strict', 'Strict'), ('standard', 'Standard'), ('relaxed', 'Relaxed')], default='standard', max_length=10),
        ),
        migrations.AddField(
            model_name='competitionsettings',
            name='results_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
