# Generated by Django 5.2.4 on 2026-08-03 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('submission_confirmed', 'Submission Confirmed'), ('eval_complete', 'Evaluation Complete'), ('results_published', 'Results Published'), ('appeal_deadline', 'Appeal Deadline Approaching'), ('appeal_resolved', 'Appeal Resolved'), ('deadline_approaching', 'Deadline Approaching'), ('general', 'General')], default='general', max_length=40)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='ix_notification_unread')],
            },
        ),
    ]
