# Generated by Django 5.2.4 on 2026-08-31 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dedupe_key',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='send_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('submission_confirmed', 'Submission Confirmed'), ('eval_complete', 'Evaluation Complete'), ('results_published', 'Results Published'), ('appeal_deadline', 'Appeal Deadline Approaching'), ('appeal_submitted', 'Appeal Submitted'), ('appeal_resolved', 'Appeal Resolved'), ('deadline_approaching', 'Deadline Approaching'), ('general', 'General')], default='general', max_length=40),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['send_email', 'sent_at'], name='ix_notification_pending'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('user', 'dedupe_key'), name='unique_notification_dedupe'),
        ),
    ]
