# Generated by Django 5.2.4 on 2026-09-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_dedupe_key_notification_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('account_created', 'Account Created'), ('email_verified', 'Email Verified'), ('invitation_sent', 'Invitation Sent'), ('invitation_accepted', 'Invitation Accepted'), ('outstanding_items', 'Outstanding Items'), ('registration_submitted', 'Registration Submitted'), ('registration_approved', 'Registration Approved'), ('registration_waitlisted', 'Registration Waitlisted'), ('registration_rejected', 'Registration Rejected'), ('registration_closing', 'Registration Closing'), ('membership_changed', 'Membership Changed'), ('policy_updated', 'Policy Updated'), ('submission_confirmed', 'Submission Confirmed'), ('eval_complete', 'Evaluation Complete'), ('results_published', 'Results Published'), ('appeal_deadline', 'Appeal Deadline Approaching'), ('appeal_submitted', 'Appeal Submitted'), ('appeal_resolved', 'Appeal Resolved'), ('deadline_approaching', 'Deadline Approaching'), ('general', 'General')], default='general', max_length=40),
        ),
    ]
